config {
    type: "operations"
}


--------------------

BEGIN TRANSACTION;
DELETE FROM  
  `aidata2025.dim.dim_ai_service_cost_unit_copy` 
where 1=1;
INSERT INTO  
  aidata2025.dim.dim_ai_service_cost_unit_copy
select 
  * 
from aidata2025.dim.dim_ai_service_cost_unit;

DELETE FROM  `aidata2025.dim.dim_collart_core_event_copy` where 1=1;
INSERT INTO  aidata2025.dim.dim_collart_core_event_copy
select * from aidata2025.dim.dim_collart_core_event;

DELETE FROM  `aidata2025.dim.dim_collart_android_core_event_copy` where 1=1;
INSERT INTO  aidata2025.dim.dim_collart_android_core_event_copy
select * from aidata2025.dim.dim_collart_android_core_event;

commit;