config {
    type : "operations",
    dependencies : "h_dwd_oper_user_event_di"
}


declare from_date date default ${dataform.projectConfig.vars.biz_date};
declare to_date date default ${dataform.projectConfig.vars.biz_date};


begin transaction;


delete from `aidata2025.dwd.dwd_id_convert_di` where event_date between from_date and to_date;

insert into `aidata2025.dwd.dwd_id_convert_di` 
with raw_data as (
    select
        event_date,
        package_name, 
        max(app_name) app_name,
        user_pseudo_id,
        array_agg(distinct if(atlasv_uid != '', atlasv_uid, null) ignore nulls) atlasv_uid,
        array_agg(distinct if(user_id != '', user_id, null) ignore nulls) user_id,
        array_agg(distinct if(` advertising_id` not in ('', "__REDACTED_ID__") , ` advertising_id`, null) ignore nulls) advertising_id,
        array_agg(distinct if(adjust_id != '', adjust_id, null) ignore nulls) adjust_id
    from aidata2025.dwd.dwd_oper_user_event_di 
    where event_date between from_date and to_date
        and user_pseudo_id is not null
    group by event_date, package_name, user_pseudo_id 
)
select 
    event_date,
    package_name,
    app_name,
    user_pseudo_id,
    atlasv_uid,
    user_id,
    advertising_id,
    adjust_id
from raw_data
left join unnest(atlasv_uid) atlasv_uid
left join unnest(user_id) user_id
left join unnest(advertising_id) advertising_id
left join unnest(adjust_id) adjust_id;

 
commit;
