module.exports = {
  PACKAGE_NAME: "collart_fashion",
  FASHION_EVENT_COVERAGE_START: "2026-06-01",
  INTERNAL_USER_IDS: [
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
    "__REDACTED_ID__",
  ],
  REVENUE_BACKFILL_DAYS: 7,
  METRIC_BACKFILL_DAYS: 60,
};
