config {
    type: "operations",
    dependencies: ["h_dwd_cdct_log_aws_cdn_di"]
}

BEGIN TRANSACTION;
  -- 这里放置一系列 DML 语句
  --删除分区数据
DELETE
FROM
  `dws.dws_cdct_log_aws_cdn_1d`
WHERE
  event_date >= DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY);
  --插入分区数据--
INSERT INTO
  dws.dws_cdct_log_aws_cdn_1d
SELECT
  event_date,
  'woolong' AS PROJECT,
  SPLIT(cs_user_agent,'/' )[SAFE_OFFSET(0)] AS os,
  SPLIT(cs_user_agent,'/' )[SAFE_OFFSET(1)] AS app_name,
  x_edge_result_type AS result_type,
  COUNT(1) AS request_cnt
FROM
  pubdata2025.dwd.dwd_cdct_log_aws_cdn_di
WHERE
  event_date >= DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY)
GROUP BY
  SPLIT(cs_user_agent,'/' )[SAFE_OFFSET(0)],
  SPLIT(cs_user_agent,'/' )[SAFE_OFFSET(1)],
  x_edge_result_type,
  event_date;
  --如果所有操作都成功，提交事务
COMMIT
  ;

